Added latex build workflow (#1)
* Added latex build workflow

* Deleted comment
Testing github action

* Changed workflow name and trigger

* Changed action trigger and artifact path

* Updating actions versions, using cache and debugging for pdf generation

* Fixed upload artifact path
Testing cache too

* Renamed main.pdf to resume.pdf

* Changed cache workflow
Based on: https://stackoverflow.com/questions/59269850/caching-apt-packages-in-github-actions-workflow

* Added dummy key in cache

* Quick fix and test of error
Error:
dpkg-query: package 'texlive' is not installed
Use dpkg --contents (= dpkg-deb --contents) to list archive files contents.
cp: missing file operand
Try 'cp --help' for more information.
Error: Process completed with exit code 123.

* Fixed texlive-full dpkg

* Changed long lines format

* Last test caching

* Testing cache

* Removed cache

* Added deployment

* Fixing deployment

* Fixing deployment: Changed artifact name

* Testing deployment
Had an error not enabling deployment with Github Pages

* Added simple index.html to see if artifact is deployed

* Changed to upload-pages-artifact action

* Fixed url action

* Gave style to index.html and renamed github action

* Renamed some steps